### PR TITLE
Add function WrapFunc, used to converts a http.HandlerFunc into a negroni.Handler

### PR DESCRIPTION
**Pull request by Tiscs**
I just add a function called WrapFunc, make easily for wrap a http.HandlerFunc into a negroni.Handler.

### CODE REVIEW

**Comment by jszwedko** [comment]
@Tiscs :+1: this looks good to me, but do you mind adding a test or two for it?

**Comment by dineshkumar-cse** [comment]
@Tiscs Is n't this similar to 
``` func (n *Negroni) UseHandlerFunc(handlerFunc func(rw http.ResponseWriter, r *http.Request)) {...}```

or How will it be used differently?

**Comment by Tiscs** [comment]
@dineshkumar-cse It's useful when you want to create a reusable and stateless handler.

**Comment by jszwedko** [comment]
One could argue that there is a bit of duplication between the `Wrap*` and `Use*` methods, but this addition does bring it into parity with `negroni.Wrap` / `negroni.UseHandler`.

:+1:

**Pull request merged**
