### PR TITLE
Combine() helper function.

### PR DESCRIPTION
**Pull request by williamhaley**
`Combine` function to address proposed enhancement in #167.

I opted to call it `Combine` instead of `Append`. I thought `Append` might imply that the original negroni is modified, like the builtin `append` does for slices, but that is not what happens here.

### CODE REVIEW

**Comment by jszwedko** [comment]
Awesome, thank you @williamhaley !

I think the implementation is great, but something feels slightly off to me about `Combine` as the method name, but I can quite place why. I agree that `append` has special semantics in Go so it'd be good to not overload that term. I'm wondering if maybe `With` could work? Then usage of the API would look something like:

```golang
router := mux.NewRouter()
apiRoutes := mux.NewRouter()

// create common middleware to be shared across routes
common := negroni.New(
    Middleware1,
    Middleware2,
)

// create a new negroni for the api middleware
// using the common middleware as a base
router.PathPrefix("/api").Handler(common.With(
  APIMiddleware1,
  negroni.Wrap(apiRoutes),
))
```

**Comment by williamhaley** [comment]
I hear ya @jszwedko. Something felt a bit off to me too about `Combine`. Maybe that's better left as a top-level function for instantiation rather than a method on an existing instance.

Anyway, I renamed to `With`, which I agree feels a bit better.

**Comment by jszwedko** [comment]
Awesome, I really like this, thanks @williamhaley

**Comment by williamhaley** [comment]
Thanks @jszwedko!

**Pull request merged**
