### PR TITLE
Allow to use header in before funcs after calling WriteHeader

### LINKED ISSUE #129: Responsewriter status in before funcs is broken
This commit https://github.com/urfave/negroni/commit/8b113cd90ea0a4dcd51cac1c8addb5ebc927532d broke the ability to retrieve the request status code inside a middleware

As you can see, status header is set before actually calling `callBefore` (https://github.com/urfave/negroni/blob/master/response_writer.go#L46-L47) so I was retrieving the status code in my before funcs. 

Now with this new validation  https://github.com/urfave/negroni/blob/master/response_writer.go#L62-L69 it's not possible anymore. 

@jszwedko

### PR DESCRIPTION
**Pull request by marcosnils**
Fixes #129

### CODE REVIEW

**Comment by jszwedko** [comment]
@marcosnils good catch, that was a mistake on my part. The current behavior (introduced in #101) is to set the status code to `200` even if the header hasn't been written yet (which causes #124). I believe this PR reintroduces that bug which reveals the fact that the test I added did not cover `Written()` as it should have.

Ultimately I think #127 addresses this by resetting the behavior back to the default to `0` for unwritten responses. I was giving time to the originators of #101 to see if they have a valid use case that required that change, but hope to merge it soon.

**Comment by marcosnils** [comment]
@jszwedko thanks for getting back so quickly. I haven't noticed #127 but I believe it's pretty much the same as this PR right?

**Comment by marcosnils** [comment]
> . I was giving time to the originators of #101 to see if they have a valid use case that required that change,

I believe it doesn't make sense to expect a `default` status from the request `before` any handlers have been called.

**Comment by jszwedko** [comment]
I agree @marcosnils and, given we've had one response, I plan on merging that work imminently.

**Comment by jszwedko** [comment]
Merged and cribbed your test into https://github.com/urfave/negroni/commit/fb7b7c045dfb05dc81a5c3688c568550b5bd6e36

**Pull request closed without merging**
