### PR TITLE
replace multiple slashes at the beginning of path with a single one

### PR DESCRIPTION
**Pull request by hhoke**
This resolves an open-redirect security vulnerability.

### CODE REVIEW

**Review by jszwedko — COMMENTED** [review]
Thanks @hhoke !

This looks good to me but do you mind adding a test for it?

**Comment by hhoke** [comment]
I am not sure how I would do it. `r.URL.Path` does not appear to be changed if I inspect it in a test, but I know that this ameliorates the security problem when used in our webapp.

**Review by jszwedko — APPROVED** [review]

**Comment by ljk5** [comment]
你们真牛逼

**Comment by ljk5** [comment]
How I couldn't find the repaired version, the awesome guy took me！

**Review by dearchap — COMMENTED** [review]
LGTFM

**Pull request merged**
