### PR TITLE
Logger display complete request url with arguments #136

### PR DESCRIPTION
**Pull request by harobed**
Logger display complete request url with arguments #136

### CODE REVIEW

**Comment by jszwedko** [comment]
Hi @harobed!

Apologies for the delay.

In my testing, `RequestURI` appeared to not be populated (and the documentation seems to point to away from using this field in lieu of `URL`). What do you think about logging `r.URL.RequestURI()` instead? Also, do you mind adding a test asserting the against the log output?

**Comment by meatballhat** [comment]
I suspect this PR can/should be combined with #158, made possible via the design change suggested in [this comment](https://github.com/urfave/negroni/pull/158#discussion_r93480483) (made by me).

**Comment by jszwedko** [comment]
👍  agreed

**Comment by meatballhat** [comment]
Please rebase on top of recently merged work, if desired :heart:

**Pull request closed without merging**
